[build]
    command = "npm run build"
    publish = "dist"
    functions = "lambda"

[context.production]
    command = "npm run build:prod"
    environment = { NODE_ENV = "production" }

[dev]
    command = "npm run serve"
    port = 8888
    targetPort = 8080
    framework = "#custom"
    environment = { NODE_ENV = "dev" }

[[redirects]]
    from = "/notes/*"
    to = "/.netlify/functions/notes"
    status = 200
    force = true